export const SAVE_EMP_REQUEST = "SAVE_EMP_REQUEST";
export const FETCH_EMP_REQUEST = "FETCH_EMP_REQUEST";
export const UPDATE_EMP_REQUEST = "UPDATE_EMP_REQUEST";
export const DELETE_EMP_REQUEST = "DELETE_EMP_REQUEST";
export const EMP_SUCCESS = "EMP_SUCCESS";
export const EMP_FAILURE = "EMP_FAILURE";

export const FETCH_DESIGNATIONS_REQUEST = "FETCH_DESIGNATIONS_REQUEST";
export const DESIGNATIONS_SUCCESS = "DESIGNATIONS_SUCCESS";
export const DESIGNATIONS_FAILURE = "DESIGNATIONS_FAILURE";

export const FETCH_DEPTS_REQUEST = "FETCH_DEPTS_REQUEST";
export const DEPTS_SUCCESS = "DEPTS_SUCCESS";
export const DEPTS_FAILURE = "DEPTS_FAILURE";
